// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHLh_t9vuq7AbfahmAyA_SkJqxKXrcrU',
    appId: '1:493103258726:web:fdc8bebe4e9c5cdaec61a7',
    messagingSenderId: '493103258726',
    projectId: 'spotify-flutter-dien1009',
    authDomain: 'spotify-flutter-dien1009.firebaseapp.com',
    storageBucket: 'spotify-flutter-dien1009.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwTFjYtimkXPQuMM2YAWnChyW-lEyTtEk',
    appId: '1:493103258726:android:004eaef1ab7d5840ec61a7',
    messagingSenderId: '493103258726',
    projectId: 'spotify-flutter-dien1009',
    storageBucket: 'spotify-flutter-dien1009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6v6OYEk364EkqYPB3r0cNXlxHkSOiKHs',
    appId: '1:493103258726:ios:3bed6dc17f9e9ef3ec61a7',
    messagingSenderId: '493103258726',
    projectId: 'spotify-flutter-dien1009',
    storageBucket: 'spotify-flutter-dien1009.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6v6OYEk364EkqYPB3r0cNXlxHkSOiKHs',
    appId: '1:493103258726:ios:3bed6dc17f9e9ef3ec61a7',
    messagingSenderId: '493103258726',
    projectId: 'spotify-flutter-dien1009',
    storageBucket: 'spotify-flutter-dien1009.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeHLh_t9vuq7AbfahmAyA_SkJqxKXrcrU',
    appId: '1:493103258726:web:cecd3ac5c7b9ac61ec61a7',
    messagingSenderId: '493103258726',
    projectId: 'spotify-flutter-dien1009',
    authDomain: 'spotify-flutter-dien1009.firebaseapp.com',
    storageBucket: 'spotify-flutter-dien1009.firebasestorage.app',
  );
}
